package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author rodri
 */
public class LLVMFrame extends javax.swing.JFrame {

    /**
     * Creates new form LLVMFrame
     */
    public LLVMFrame() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        sourceScroll = new javax.swing.JScrollPane();
        sourceTextArea = new javax.swing.JTextArea();
        llvmScroll = new javax.swing.JScrollPane();
        llvmTextArea = new javax.swing.JTextArea();
        machineScroll = new javax.swing.JScrollPane();
        machineTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuLLVM = new javax.swing.JMenu();
        itmeCompileLLVM = new javax.swing.JMenuItem();
        itemSaveLLVM = new javax.swing.JMenuItem();
        itemCompileLLVMToNative = new javax.swing.JMenuItem();
        itemRunLLVM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LLVM - Triangle");
        setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        setIconImage(new ImageIcon(this.getClass().getResource("Icons/iconMain.gif")).getImage());
        setMinimumSize(new java.awt.Dimension(208, 36));
        setPreferredSize(new java.awt.Dimension(766, 400));

        sourceTextArea.setEditable(false);
        sourceTextArea.setColumns(20);
        sourceTextArea.setRows(5);
        sourceScroll.setViewportView(sourceTextArea);

        jTabbedPane1.addTab("Código fuente Triangle", sourceScroll);

        llvmTextArea.setEditable(false);
        llvmTextArea.setColumns(20);
        llvmTextArea.setRows(5);
        llvmScroll.setViewportView(llvmTextArea);

        jTabbedPane1.addTab("Código LLVM (IR)", llvmScroll);

        machineTextArea.setEditable(false);
        machineTextArea.setColumns(20);
        machineTextArea.setRows(5);
        machineScroll.setViewportView(machineTextArea);

        jTabbedPane1.addTab("Código máquina", machineScroll);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        MenuLLVM.setText("LLVM");

        itmeCompileLLVM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconTriangleCompile.gif"))); // NOI18N
        itmeCompileLLVM.setText("Compilar a LLVM");
        itmeCompileLLVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmeCompileLLVMActionPerformed(evt);
            }
        });
        MenuLLVM.add(itmeCompileLLVM);

        itemSaveLLVM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconFileSave.gif"))); // NOI18N
        itemSaveLLVM.setText("Guardar código LLVM");
        itemSaveLLVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveLLVMActionPerformed(evt);
            }
        });
        MenuLLVM.add(itemSaveLLVM);

        itemCompileLLVMToNative.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconFileNew.gif"))); // NOI18N
        itemCompileLLVMToNative.setText("Compilar LLVM a código nativo");
        itemCompileLLVMToNative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompileLLVMToNativeActionPerformed(evt);
            }
        });
        MenuLLVM.add(itemCompileLLVMToNative);

        itemRunLLVM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconTriangleRun.gif"))); // NOI18N
        itemRunLLVM.setText("Ejecutar código LLVM en Shell");
        itemRunLLVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRunLLVMActionPerformed(evt);
            }
        });
        MenuLLVM.add(itemRunLLVM);

        jMenuBar1.add(MenuLLVM);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmeCompileLLVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmeCompileLLVMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmeCompileLLVMActionPerformed

    private void itemSaveLLVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveLLVMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSaveLLVMActionPerformed

    private void itemCompileLLVMToNativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompileLLVMToNativeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCompileLLVMToNativeActionPerformed

    private void itemRunLLVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRunLLVMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRunLLVMActionPerformed

    
    // <editor-fold defaultstate="collapsed" desc=" Metodos ">
    
    // <editor-fold>
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LLVMFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLLVM;
    private javax.swing.JMenuItem itemCompileLLVMToNative;
    private javax.swing.JMenuItem itemRunLLVM;
    private javax.swing.JMenuItem itemSaveLLVM;
    private javax.swing.JMenuItem itmeCompileLLVM;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane llvmScroll;
    private javax.swing.JTextArea llvmTextArea;
    private javax.swing.JScrollPane machineScroll;
    private javax.swing.JTextArea machineTextArea;
    private javax.swing.JScrollPane sourceScroll;
    private javax.swing.JTextArea sourceTextArea;
    // End of variables declaration//GEN-END:variables
}
