package GUI;

import Triangle.IDEMultiBackendCompiler;
import Triangle.IDEMultiBackendCompiler.BackendType;
import Triangle.LLVMCompiler;
import Triangle.LLVMCompilerEXE;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
 
public class LLVMFrame extends javax.swing.JFrame {

    /**
     * Creates new form LLVMFrame
     */
    public LLVMFrame() {
        initComponents(); 
        itemSaveLLVM.setEnabled(false);
        itemCompileLLVMToNative.setEnabled(false);
        itemRunMachineCode.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        sourceScroll = new javax.swing.JScrollPane();
        sourceTextArea = new javax.swing.JTextArea();
        llvmScroll = new javax.swing.JScrollPane();
        llvmTextArea = new javax.swing.JTextArea();
        machineScroll = new javax.swing.JScrollPane();
        machineTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuLLVM = new javax.swing.JMenu();
        itmeCompileLLVM = new javax.swing.JMenuItem();
        itemSaveLLVM = new javax.swing.JMenuItem();
        itemCompileLLVMToNative = new javax.swing.JMenuItem();
        itemRunMachineCode = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LLVM - Triangle");
        setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        setIconImage(new ImageIcon(this.getClass().getResource("Icons/iconMain.gif")).getImage());
        setMinimumSize(new java.awt.Dimension(208, 36));
        setPreferredSize(new java.awt.Dimension(766, 400));

        sourceTextArea.setEditable(false);
        sourceTextArea.setColumns(20);
        sourceTextArea.setRows(5);
        sourceScroll.setViewportView(sourceTextArea);

        jTabbedPane1.addTab("Código fuente Triangle", sourceScroll);

        llvmTextArea.setColumns(20);
        llvmTextArea.setRows(5);
        llvmScroll.setViewportView(llvmTextArea);

        jTabbedPane1.addTab("Código LLVM (IR)", llvmScroll);

        machineTextArea.setEditable(false);
        machineTextArea.setColumns(20);
        machineTextArea.setRows(5);
        machineScroll.setViewportView(machineTextArea);

        jTabbedPane1.addTab("Código máquina", machineScroll);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        MenuLLVM.setText("LLVM");

        itmeCompileLLVM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconTriangleCompile.gif"))); // NOI18N
        itmeCompileLLVM.setText("Compilar a LLVM");
        itmeCompileLLVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmeCompileLLVMActionPerformed(evt);
            }
        });
        MenuLLVM.add(itmeCompileLLVM);

        itemSaveLLVM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconFileSave.gif"))); // NOI18N
        itemSaveLLVM.setText("Guardar código LLVM");
        itemSaveLLVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveLLVMActionPerformed(evt);
            }
        });
        MenuLLVM.add(itemSaveLLVM);

        itemCompileLLVMToNative.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconFileNew.gif"))); // NOI18N
        itemCompileLLVMToNative.setText("Compilar LLVM a código nativo");
        itemCompileLLVMToNative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompileLLVMToNativeActionPerformed(evt);
            }
        });
        MenuLLVM.add(itemCompileLLVMToNative);

        itemRunMachineCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/iconTriangleRun.gif"))); // NOI18N
        itemRunMachineCode.setText("Ejecutar código LLVM en Shell");
        itemRunMachineCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRunMachineCodeActionPerformed(evt);
            }
        });
        MenuLLVM.add(itemRunMachineCode);

        jMenuBar1.add(MenuLLVM);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // <editor-fold defaultstate="collapsed" desc="Metodos ">
    
    private void itmeCompileLLVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmeCompileLLVMActionPerformed
        compileToLLVM();
    }//GEN-LAST:event_itmeCompileLLVMActionPerformed

    private void itemSaveLLVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveLLVMActionPerformed
        
        if (!llvmCodeGenerated || llvmTextArea.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay código LLVM para guardar.\nPrimero compila el código.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Guardar código LLVM");

        // Obtener la ruta original del archivo .tri
        String originalPath = sourceTextArea.getToolTipText();
        if (originalPath != null && !originalPath.isEmpty()) {
            File originalFile = new File(originalPath);
            if (originalFile.exists()) {
                chooser.setCurrentDirectory(originalFile.getParentFile());
                chooser.setSelectedFile(new File(originalFile.getName().replace(".tri", ".ll")));
            }
        } else {
            chooser.setSelectedFile(new File("output.ll")); // fallback
        }

        int result = chooser.showSaveDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if (!file.getName().endsWith(".ll")) {
                file = new File(file.getAbsolutePath() + ".ll");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
                writer.write(llvmTextArea.getText());
                JOptionPane.showMessageDialog(this, "Código LLVM guardado exitosamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_itemSaveLLVMActionPerformed

    private void itemCompileLLVMToNativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompileLLVMToNativeActionPerformed
        String llvmCode = llvmTextArea.getText();
        if (llvmCode.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay código LLVM para compilar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String basePath = sourceTextArea.getToolTipText().replace(".tri", "");
            String exePath = LLVMCompilerEXE.compileLLVMToEXE(llvmCode, basePath);

            String assembly = LLVMCompiler.compileLLVMToAssembly(llvmCode); 
            machineTextArea.setText("=== Ensamblador generado ===\n" + assembly +
                                    "\n\n=== Ejecutable generado ===\n" + exePath);
            jTabbedPane1.setSelectedIndex(2);

            // Habilitar ejecutar
            itemRunMachineCode.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al compilar LLVM:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_itemCompileLLVMToNativeActionPerformed

    private void itemRunMachineCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRunMachineCodeActionPerformed
        String llvmCode = llvmTextArea.getText();
        if (llvmCode.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay código LLVM para ejecutar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        try {
            String basePath = sourceTextArea.getToolTipText().replace(".tri", "");
            File exeFile = new File(basePath + "_ejecutables\\programa.exe");

            if (!exeFile.exists()) {
                JOptionPane.showMessageDialog(this, "No se encontró el ejecutable.\nPrimero compilá a código nativo.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Abrir terminal 
            LLVMCompilerEXE.runEXEWithBat(exeFile.getAbsolutePath());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al ejecutar:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemRunMachineCodeActionPerformed

    /* 
        Recibe el código fuente Triangle y lo muestra en la pestaña correspondiente
    */
    public void setSourceText(String code, String filePath) {
        sourceTextArea.setText(code);
        sourceTextArea.setToolTipText(filePath); // ? para recordar la ruta
        jTabbedPane1.setSelectedIndex(0);
     }
        
    public void compileToLLVM() {
        String sourceCode = sourceTextArea.getText();
        if (sourceCode == null || sourceCode.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay código fuente para compilar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear archivo temporal .tri
        File tempFile = null;
        try {
            tempFile = File.createTempFile("triangle_temp", ".tri");
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile))) {
                bw.write(sourceCode);
            }

            // Compilar usando el multi-backend compiler con LLVM_IR
            IDEMultiBackendCompiler compiler = new IDEMultiBackendCompiler();
            boolean success = compiler.compileProgram(tempFile.getAbsolutePath(), BackendType.LLVM_IR);

            if (success) {
                String llvmFile = tempFile.getAbsolutePath().replace(".tri", ".ll");
                String llvmCode = readFileAsString(llvmFile);
                llvmTextArea.setText(llvmCode);
                
                llvmCodeGenerated = true; 
                itemSaveLLVM.setEnabled(true);
                itemCompileLLVMToNative.setEnabled(true); 
                itemCompileLLVMToNative.setEnabled(true);
                // Cambiar a pestaña LLVM
                jTabbedPane1.setSelectedIndex(1); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al compilar a LLVM IR.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Excepción durante la compilación: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (tempFile != null) tempFile.delete();
        }
    }

    // Método auxiliar para leer archivo
    private String readFileAsString(String filePath) throws Exception {
        StringBuilder sb = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
        }
        return sb.toString();
    }
     
    // [ End of Metodos ]
    // </editor-fold>
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LLVMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LLVMFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLLVM;
    private javax.swing.JMenuItem itemCompileLLVMToNative;
    private javax.swing.JMenuItem itemRunMachineCode;
    private javax.swing.JMenuItem itemSaveLLVM;
    private javax.swing.JMenuItem itmeCompileLLVM;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane llvmScroll;
    private javax.swing.JTextArea llvmTextArea;
    private javax.swing.JScrollPane machineScroll;
    private javax.swing.JTextArea machineTextArea;
    private javax.swing.JScrollPane sourceScroll;
    private javax.swing.JTextArea sourceTextArea;
    // End of variables declaration//GEN-END:variables
    private boolean llvmCodeGenerated = false;
}
